import type { GalleryData } from "./types";
export const demoData: GalleryData = {
  profile: {
    name: { zh: "林间来信", en: "Letters from the Garden" },
    tagline: {
      zh: "把那些细小的、闪光的瞬间，画成一个世界。",
      en: "Small wonders, quietly gathered. A world told in colour.",
    },
    bio: {
      zh: "你好，我是一位喜欢植物、故事与奇妙生物的插画师。这里收藏着我的创作片段：一阵风、一场梦，以及日常生活里值得停留的微小瞬间。\n\n这是示例画廊。真实的画师介绍、作品与联系方式可以在后台替换。",
      en: "Hello. I’m an illustrator drawn to botanical worlds, quiet stories, and curious little creatures. This is a collection of passing moments — a breeze, a dream, a small reason to pause.\n\nThis is a demo gallery. The artist’s real biography, artworks and contact details can be edited in the studio.",
    },
    email: "",
    instagram: "",
    contact: "",
  },
  collections: [
    {
      id: "botanical",
      slug: "botanical-dreams",
      title: { zh: "花与未完成的梦", en: "Botanical dreams" },
      description: {
        zh: "在枝叶之间，收集一些缓慢生长的故事。",
        en: "Stories that grow slowly, somewhere between the leaves.",
      },
      status: "published",
      position: 0,
      coverId: "art-1",
      deletedAt: null,
      version: 1,
    },
    {
      id: "quiet",
      slug: "quiet-places",
      title: { zh: "风停留的地方", en: "Where the wind rests" },
      description: {
        zh: "远方的山、温柔的光，还有不必着急的时刻。",
        en: "Distant hills, gentle light, and moments without a hurry.",
      },
      status: "published",
      position: 1,
      coverId: "art-2",
      deletedAt: null,
      version: 1,
    },
    {
      id: "little",
      slug: "little-wonders",
      title: { zh: "小小的奇遇", en: "Little wonders" },
      description: {
        zh: "给平凡日常的一点奇思妙想。",
        en: "A little imagination for ordinary days.",
      },
      status: "published",
      position: 2,
      coverId: "art-3",
      deletedAt: null,
      version: 1,
    },
  ],
  artworks: Array.from({ length: 9 }, (_, i) => ({
    id: `art-${i + 1}`,
    collectionId: ["botanical", "quiet", "little"][i % 3],
    title: {
      zh: [
        "月下花园",
        "远山来信",
        "橘色午后",
        "向光生长",
        "日落以前",
        "一朵小星星",
        "静静盛开",
        "山间的风",
        "柔软时刻",
      ][i],
      en: [
        "Moonlit garden",
        "Letters from the hills",
        "An orange afternoon",
        "Growing toward light",
        "Before sunset",
        "A little star",
        "Quietly blooming",
        "Mountain breeze",
        "Soft moments",
      ][i],
    },
    description: {
      zh: "原创矢量示例图，用于展示画廊布局；并非画师真实作品。",
      en: "Original vector demo artwork for layout preview, not the artist’s actual work.",
    },
    alt: {
      zh: [
        "深绿背景上的植物与花朵",
        "日落下的层叠山丘",
        "暖色背景上的抽象花朵",
      ][i % 3],
      en: [
        "Botanical flowers on a deep green background",
        "Layered hills beneath a setting sun",
        "Abstract blossoms on warm paper",
      ][i % 3],
    },
    year: "2026",
    status: "published" as const,
    position: Math.floor(i / 3),
    assetId: `asset-${i + 1}`,
    deletedAt: null,
    version: 1,
  })),
  assets: Array.from({ length: 9 }, (_, i) => ({
    id: `asset-${i + 1}`,
    fileId: "",
    url: `/art/plate-${(i % 3) + 1}.svg`,
    width: 800,
    height: 1000,
    bytes: 0,
    verified: true,
    isPrivate: false,
  })),
};
